export const Plan = {
  plan_St80kbVck5HN6t: {
    storageQuotaInBytes: 2 * 1024 ** 4,
    name: "Plus",
    level: 1,
    price: 199,
    billingCycle: "monthly",
    features: [
      "2 TB secure cloud storage",
      "Fast uploads & downloads",
      "Cross-device sync",
      "File sharing",
    ],
  },
  plan_SreGUKh5S8Ajhh: {
    storageQuotaInBytes: 5 * 1024 ** 4,
    name: "Pro",
    level: 2,
    price: 399,
    billingCycle: "monthly",
    features: [
      "5 TB secure cloud storage",
      "Priority syncing",
      "30-day file recovery",
      "Advanced sharing controls",
      "Faster transfer speeds",
    ],
  },
  plan_StfZUyL605I6A9: {
    storageQuotaInBytes: 10 * 1024 ** 4,
    name: "Ultra",
    level: 3,
    price: 4999,
    billingCycle: "monthly",
    features: [
      "10 TB secure cloud storage",
      "Maximum upload speed",
      "Encrypted backups",
      "Priority support",
      "Advanced recovery tools",
    ],
  },
  plan_SreJ2zeFpdsulz: {
    storageQuotaInBytes: 2 * 1024 ** 4,
    name: "Plus",
    level: 1,
    price: 1990,
    billingCycle: "yearly",
    features: [
      "2 TB secure cloud storage",
      "Fast uploads & downloads",
      "Cross-device sync",
      "File sharing",
    ],
  },
   plan_SreG4IFOAQg2Bp: {
    storageQuotaInBytes: 5 * 1024 ** 4,
    name: "Pro",
    level: 2,
    price: 3999,
    billingCycle: "yearly",
    features: [
      "5 TB secure cloud storage",
      "Priority syncing",
      "30-day file recovery",
      "Advanced sharing controls",
      "Faster transfer speeds",
    ],
  },
  plan_SreBn93KlV0Tua: {
    storageQuotaInBytes: 10 * 1024 ** 4,
    name: "Ultra",
    level: 3,
    price: 6990,
    billingCycle: "yearly",
    features: [
      "10 TB secure cloud storage",
      "Maximum upload speed",
      "Encrypted backups",
      "Priority support",
      "Advanced recovery tools",
    ],
  },
};